name: Render Badges

on: [pull_request, pull_request_target]


permissions:
  id-token: write
  contents: write
  pull-requests: read

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  render_badgets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Check out repository to the runner
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Run render_badges.sh
        run: bash render_badges.sh

      - name: Commit files
        run: |
          git config --local user.email "195262995+facsimilab-bot@users.noreply.github.com"
          git config --local user.name "FacsimiLab [Bot]"
          git commit -a -m "ci: Render themed badges"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.head_ref }}
