name: Render Badges

permissions:
  id-token: write
  contents: write
  pull-requests: read

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Check out repository to the runner

      - name: Run render_badges.sh
        run: bash render_badges.sh

      - name: Commit files
        run: |
          git config --local user.email "action@noreply.github.com"
          git config --local user.name "GitHub Action"
          git commit -a -m "ci: Render themed badges"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
