name: Render Badges

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  pull_request_target:
  


permissions:
  id-token: write
  contents: write
  pull-requests: read

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  render_badges:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Check out repository to the runner
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 5

      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.FACSIMILAB_BOT_SSHKEY }}
      - run: |
          bash render_badges.sh
          git config --local user.email "195262995+facsimilab-bot@users.noreply.github.com"
          git config --local user.name "FacsimiLab [Bot]"
          git config --local user.signingkey "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAEjI+PVQQhQjLVRmB6NnDJhqXKaVjzcr4KG1vqMkd2m  FacsimiLab [Bot]"
          git commit -a -S -m "ci: Render themed badges"
          git push
