name: Render Badges

on: 
  pull_request:
    branches:
      - main
    types: [opened, ready_for_review, reopened]
  


permissions:
  id-token: write
  contents: write
  pull-requests: read

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  render_badges:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Check out repository to the runner
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 5

      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.FACSIMILAB_BOT_SSHKEY }}
        
      - name: render, commit, and push
        run: |
          bash render_badges.sh
          git config --local user.email "195262995+facsimilab-bot@users.noreply.github.com"
          git config --local user.name "FacsimiLab [Bot]"
          git config --local user.signingkey "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAEjI+PVQQhQjLVRmB6NnDJhqXKaVjzcr4KG1vqMkd2m  FacsimiLab [Bot]"
          git config --local gpg.format ssh
          git config --local commit.gpgsign true
          git config --local tag.gpgSign true


          if [ -n "$(git status --porcelain)" ]; then
            git commit -a -S -m "ci: Render themed badges"
          else
            echo "No changes to commit"
          fi


          git push


      - name: Request review based on files changes and/or groups the author belongs to
        uses: necojackarc/auto-request-review@v0.13.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config: .github/reviewers.yml # Config file location override