name: Render Badges

permissions: # Global permissions configuration starts here
  contents: read # 'read' access to repository contents
  pull-requests: write # 'write' access to pull requests

on:
  push:
    branches:
      - "develop"

  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"
      tags:
        description: "Manual run of render_badges.sh"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.

      - name: Run render_badges.sh
        run: bash render_badges.sh

      - name: Commit files
        run: |
          git config --local user.email "62562712+pranavmishra90@users.noreply.github.com"
          git config --local user.name "GitHub Action for pranavmishra90"
          git commit -a -m "Render themed badges"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          branch: develop

      - name: Create/Update Pull Request
        run: |
          PR_TITLE="Updated render of badges"
          PR_BODY="This pull request updates the rendered badges."
          PR_BRANCH="develop"
          PR_TARGET_BRANCH="main"
          PR_URL=$(curl -X GET -s -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" "https://api.github.com/repos/${GITHUB_REPOSITORY}/pulls?state=open" | jq -r ".[0].html_url")

          if [ -z "$PR_URL" ]; then
            # No open pull requests found, create a new one
            curl -X POST -s -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" -H "Content-Type: application/json" -d "{\"title\":\"$PR_TITLE\",\"body\":\"$PR_BODY\",\"head\":\"$PR_BRANCH\",\"base\":\"$PR_TARGET_BRANCH\"}" "https://api.github.com/repos/${GITHUB_REPOSITORY}/pulls"
          else
            # Update the latest open pull request
            PR_NUMBER=$(echo $PR_URL | awk -F'/' '{print $NF}')
            curl -X PATCH -s -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" -H "Content-Type: application/json" -d "{\"title\":\"$PR_TITLE\",\"body\":\"$PR_BODY\"}" "https://api.github.com/repos/${GITHUB_REPOSITORY}/pulls/$PR_NUMBER"
          fi
